# This is a basic workflow to help you get started with Actions

name: CI simple Hello App to GKE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Setup and Deploy
    runs-on: ubuntu-latest  
    # Add "id-token" with intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
         credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
