name: Deploy simple hello app to GKE

on:
  push:
    branches:
    - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: gks-demo-dev    # TODO: update to cluster name
  GKE_ZONE: us-central1-a	   # TODO: update to cluster zone
  DEPLOYMENT_NAME: gke-hello-app # TODO: update deployment name if changed in deployment.yaml
